[package]
name = "nahpu_images"
version = "0.1.0"
edition = "2024"
authors = ["Heru Handika <herubiolog@gmail.com>"]
description = "A utility crate for image processing and conversion."
repository = "https://github.com/hhandika/nahpu_api"
license = "MIT"
keywords = ["spatial", "gis", "geojson", "kml", "shapefile"]
categories = ["science"]
readme = "README.md"
homepage = "https://www.nahpu.app/"

[dependencies]
image = "0.25.10"
little_exif = "0.6.23"
