[package]
name = "nahpu_images"
version = "0.1.0"
edition = "2024"
authors = ["Heru Handika <herubiolog@gmail.com>"]
description = "A utility crate for image processing and conversion."
repository = "https://github.com/hhandika/nahpu_api"
license = "MIT"
keywords = ["image", "resize", "jpeg", "png", "webp"]
categories = ["multimedia::images"]
readme = "README.md"
homepage = "https://www.nahpu.app/"

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
little_exif = "0.6.23"
tempfile = "3.27.0"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.27.0"
