// This file is auto-generated by build.rs. Do not edit directly.
// It is derived from the NAHPU Drift schema (CREATE TABLE statements only).
// Source: https://raw.githubusercontent.com/nahpu/nahpu/main/lib/services/database/tables.drift
// Regenerate by running `cargo build`.

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Site {
    pub id: i32,
    pub site_id: Option<String>,
    pub project_uuid: Option<String>,
    pub lead_staff_id: Option<String>,
    pub site_type: Option<String>,
    pub country: Option<String>,
    pub state_province: Option<String>,
    pub county: Option<String>,
    pub municipality: Option<String>,
    pub media_id: Option<String>,
    pub locality: Option<String>,
    pub remark: Option<String>,
    pub habitat_type: Option<String>,
    pub habitat_condition: Option<String>,
    pub habitat_description: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Coordinate {
    pub id: Option<i32>,
    pub name_id: Option<String>,
    pub decimal_latitude: Option<f64>,
    pub decimal_longitude: Option<f64>,
    pub elevation_in_meter: Option<f64>,
    pub datum: Option<String>,
    pub uncertainty_in_meters: Option<i32>,
    pub gps_unit: Option<String>,
    pub notes: Option<String>,
    pub site_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CollEvent {
    pub id: i32,
    pub id_suffix: Option<String>,
    pub project_uuid: Option<String>,
    pub start_date: Option<String>,
    pub start_time: Option<String>,
    pub end_date: Option<String>,
    pub end_time: Option<String>,
    pub primary_coll_method: Option<String>,
    pub coll_method_notes: Option<String>,
    pub site_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Weather {
    pub event_id: Option<i32>,
    pub lowest_day_temp_c: Option<f64>,
    pub highest_day_temp_c: Option<f64>,
    pub lowest_night_temp_c: Option<f64>,
    pub highest_night_temp_c: Option<f64>,
    pub average_humidity: Option<f64>,
    pub dew_point_temp: Option<f64>,
    pub sunrise_time: Option<String>,
    pub sunset_time: Option<String>,
    pub moon_phase: Option<String>,
    pub notes: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CollPersonnel {
    pub id: i32,
    pub event_id: Option<i32>,
    pub personnel_id: Option<String>,
    pub name: Option<String>,
    pub role: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CollEffort {
    pub id: i32,
    pub event_id: Option<i32>,
    pub method: Option<String>,
    pub brand: Option<String>,
    pub count: Option<i32>,
    pub size: Option<String>,
    pub notes: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Narrative {
    pub id: i32,
    pub project_uuid: Option<String>,
    pub date: Option<String>,
    pub site_id: Option<i32>,
    pub narrative: Option<String>,
    pub media_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Media {
    pub primary_id: i32,
    pub project_uuid: Option<String>,
    pub secondary_id: Option<String>,
    pub category: Option<String>,
    pub tag: Option<String>,
    pub taken: Option<String>,
    pub camera: Option<String>,
    pub lenses: Option<String>,
    pub additional_exif: Option<String>,
    pub personnel_id: Option<String>,
    pub file_name: Option<String>,
    pub caption: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct NarrativeMedia {
    pub narrative_id: i32,
    pub media_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct SiteMedia {
    pub site_id: i32,
    pub media_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct SpecimenMedia {
    pub specimen_uuid: String,
    pub media_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct AssociatedData {
    pub primary_id: Option<i32>,
    pub specimen_uuid: Option<String>,
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub type_: Option<String>,
    pub date: Option<String>,
    pub description: Option<String>,
    pub url: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PersonnelList {
    pub project_uuid: Option<String>,
    pub personnel_uuid: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Personnel {
    pub uuid: String,
    pub name: Option<String>,
    pub initial: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub affiliation: Option<String>,
    pub role: Option<String>,
    pub current_field_number: Option<i32>,
    pub notes: Option<String>,
    pub photo_path: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Taxonomy {
    pub id: i32,
    pub taxon_class: Option<String>,
    pub taxon_order: Option<String>,
    pub taxon_family: Option<String>,
    pub genus: Option<String>,
    pub specific_epithet: Option<String>,
    pub authors: Option<String>,
    pub common_name: Option<String>,
    pub notes: Option<String>,
    pub cites_status: Option<String>,
    pub red_list_category: Option<String>,
    pub country_status: Option<String>,
    pub sorting_order: Option<i32>,
    pub media_id: Option<i32>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Specimen {
    pub uuid: String,
    pub project_uuid: Option<String>,
    pub species_id: Option<i32>,
    pub i_d_confidence: Option<i32>,
    pub i_d_method: Option<String>,
    pub taxon_group: Option<String>,
    pub condition: Option<String>,
    pub prep_date: Option<String>,
    pub prep_time: Option<String>,
    pub collection_date: Option<String>,
    pub collection_time: Option<String>,
    pub capture_date: Option<String>,
    pub is_relative_time: Option<i32>,
    pub capture_time: Option<String>,
    pub trap_type: Option<String>,
    pub method_id: Option<String>,
    pub coordinate_id: Option<i32>,
    pub cataloger_id: Option<String>,
    pub field_number: Option<i32>,
    pub coll_event_id: Option<i32>,
    pub is_multiple_collector: Option<i32>,
    pub coll_personnel_id: Option<i32>,
    pub coll_method_id: Option<i32>,
    pub museum_id: Option<String>,
    pub preparator_id: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct MammalMeasurement {
    pub specimen_uuid: String,
    pub total_length: Option<f64>,
    pub tail_length: Option<f64>,
    pub hind_foot_length: Option<f64>,
    pub ear_length: Option<f64>,
    pub forearm: Option<f64>,
    pub weight: Option<f64>,
    pub accuracy: Option<String>,
    pub accuracy_specify: Option<String>,
    pub sex: Option<i32>,
    pub age: Option<i32>,
    pub testis_position: Option<i32>,
    pub testis_length: Option<f64>,
    pub testis_width: Option<f64>,
    pub epididymis_appearance: Option<i32>,
    pub reproductive_stage: Option<i32>,
    pub left_placental_scars: Option<i32>,
    pub right_placental_scars: Option<i32>,
    pub mammae_condition: Option<i32>,
    pub mammae_inguinal_count: Option<i32>,
    pub mammae_axillary_count: Option<i32>,
    pub mammae_abdominal_count: Option<i32>,
    pub vagina_opening: Option<i32>,
    pub pubic_symphysis: Option<i32>,
    pub embryo_left_count: Option<i32>,
    pub embryo_right_count: Option<i32>,
    pub embryo_cr: Option<i32>,
    pub remark: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct AvianMeasurement {
    pub specimen_uuid: String,
    pub weight: Option<f64>,
    pub wingspan: Option<f64>,
    pub iris_color: Option<String>,
    pub iris_hex: Option<String>,
    pub bill_color: Option<String>,
    pub bill_hex: Option<String>,
    pub foot_color: Option<String>,
    pub foot_hex: Option<String>,
    pub tarsus_color: Option<String>,
    pub tarsus_hex: Option<String>,
    pub sex: Option<i32>,
    pub brood_patch: Option<i32>,
    pub skull_ossification: Option<i32>,
    pub has_bursa: Option<i32>,
    pub bursa_width: Option<f64>,
    pub bursa_length: Option<f64>,
    pub fat: Option<i32>,
    pub stomach_content: Option<String>,
    pub testis_length: Option<f64>,
    pub testis_width: Option<f64>,
    pub testis_remark: Option<String>,
    pub ovary_length: Option<f64>,
    pub ovary_width: Option<f64>,
    pub oviduct_width: Option<f64>,
    pub ovary_appearance: Option<i32>,
    pub first_ova_size: Option<f64>,
    pub second_ova_size: Option<f64>,
    pub third_ova_size: Option<f64>,
    pub oviduct_appearance: Option<i32>,
    pub ovary_remark: Option<String>,
    pub wing_is_molt: Option<i32>,
    pub wing_molt: Option<String>,
    pub tail_is_molt: Option<i32>,
    pub tail_molt: Option<String>,
    pub body_molt: Option<i32>,
    pub molt_remark: Option<String>,
    pub specimen_remark: Option<String>,
    pub habitat_remark: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct SpecimenPart {
    pub id: Option<i32>,
    pub specimen_uuid: Option<String>,
    pub personnel_id: Option<String>,
    pub tissue_id: Option<String>,
    pub barcode_id: Option<String>,
    #[serde(rename = "type")]
    pub type_: Option<String>,
    pub count: Option<String>,
    pub treatment: Option<String>,
    pub additional_treatment: Option<String>,
    pub date_taken: Option<String>,
    pub time_taken: Option<String>,
    pub pmi: Option<String>,
    pub museum_permanent: Option<String>,
    pub museum_loan: Option<String>,
    pub remark: Option<String>,
}


