name: Release

on:
  push:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish nahpu_dwc
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATE_IO_NAHPU_API }}
        run: cargo publish -p nahpu_dwc

      - name: Publish nahpu_archive
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATE_IO_NAHPU_API }}
        run: cargo publish -p nahpu_archive
